---
title: "Step 7. Calculating estimates"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{7_estimate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style type = "text/css">
h1.title {
  font-size: 30px;
}
h1 { /* Header 1 */
  font-size: 26px;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 16px;
}
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(rmarkdown.html_vignette.check_title = FALSE)

library(readr)
library(ggplot2)
```

```{r setup, include = FALSE}
devtools::load_all()
#library(geocausal)
```

```{r load data, include = FALSE}
dat_hfr <- readRDS("~/geocausal/Data/dat_hfr_4.rds")
load("~/geocausal/Data/iraq_window.Rda")
load("~/geocausal/Data/windows.RData")
load("~/geocausal/Data/counter_d.Rda")
obs_density_surge <- readRDS("~/geocausal/Data/obs_density_surge.rds")
```


# 1. Get estimates

```{r}
# Sum of counterfactual log densities
# Note: counter_d is a list of two counterfactual densities
counter_d1 <- counter_d[[1]] #Mosul x roads
counter_d2 <- counter_d[[2]] #Mosul x Bagh

# Run fx for counter_d1
estimates_counter_mosul <- get_estimates(obs_dens = obs_density_surge,
                                         cf_dens = counter_d1,
                                         treatment_data = dat_hfr$Airstrike,
                                         smoothed_outcome = dat_hfr$smooth_allout,
                                         lag = 3,
                                         entire_window = iraq_window,
                                         dist_map = dist_from_focus$distance_im,
                                         dist_map_unit = "km",
                                         grayscale = FALSE,
                                         use_raw = TRUE)

estimates_counter_mosul$plot
```

With another couterfactual scenario (Baghdad focus)

```{r}
estimates_counter_bagh <- get_estimates(obs_dens = obs_density_surge,
                                        cf_dens = counter_d2,
                                        treatment_data = dat_hfr$Airstrike,
                                        smoothed_outcome = dat_hfr$smooth_allout,
                                        lag = 3,
                                        entire_window = iraq_window,
                                        dist_map = dist_from_focus$distance_im,
                                        dist_map_unit = "km",
                                        grayscale = FALSE,
                                        use_raw = TRUE)

estimates_counter_bagh$plot

# Need to increase the resolution, ideally at least 256 x 256
# lag for M as well (one lag)
```

```{r}
# Get the causal contrasts (with CI)
causal_contrast <- get_causal_cont(scenario_1 = estimates_counter_mosul,
                                   scenario_2 = estimates_counter_bagh,
                                   grayscale = FALSE,
                                   use_raw = TRUE)

causal_contrast$plot
```

How about from outcome locations? Or multiple maps at once?



